name: pipeline

on:
  push:
    branches: [github-actions]
    # branches: [dev, stg, prd]
    paths-ignore:
      - "README.md"

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ### --------------------------------------------------
      ### Find and Replace - YAML anchors are not supported
      TF_VAR_app_name: tfmultienv
      TF_VAR_region: eu-west-1
      AWS_REGION: eu-west-1
      AWS_DEFAULT_REGION: eu-west-1
      ### --------------------------------------------------
      LIVE_DIR: live
      BACKEND_TPL: backend.tf.tpl

    steps:
      - uses: actions/checkout@v2
      - uses: chrislennon/action-aws-cli@v1.1
        name: Install AWS CLI
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x
      - name: Set AWS credentials as env vars
        run: |
          echo "::set-env name=AWS_ACCESS_KEY_ID_SECRET_NAME::AWS_ACCESS_KEY_ID_${GITHUB_REF_SLUG}"
          echo "::set-env name=AWS_SECRET_ACCESS_KEY_SECRET_NAME::AWS_SECRET_ACCESS_KEY_${GITHUB_REF_SLUG}"
      - name: prepare-files-folders
        run: |
          ./scripts/prepare-files-folders.sh
      - name: prepare-backend
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets[env.AWS_ACCESS_KEY_ID_SECRET_NAME] }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets[env.AWS_SECRET_ACCESS_KEY_SECRET_NAME] }}        
          ./scripts/prepare-backend.sh
      - name: install-terraform
        uses: little-core-labs/install-terraform@v1
        with:
          version: 0.13.1
      - name: terraform-apply
        run: |
          export AWS_ACCESS_KEY_ID=${{ secrets[env.AWS_ACCESS_KEY_ID_SECRET_NAME] }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets[env.AWS_SECRET_ACCESS_KEY_SECRET_NAME] }}        
          ./scripts/terraform-apply.sh
